#!/bin/sh
command -v gtk-update-icon-cache   >/dev/null 2>&1 && gtk-update-icon-cache -f /usr/share/icons/hicolor/ || true
command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database /usr/share/applications/   || true
